### ISSUE TITLE
Healdruid

### ISSUE THREAD

**Issue by jonasd1** [Bin4ry1337/Profiles#7]
Hey, this is not really an issue but I have no clue how that request thingy works :D 

I'd love to see a simple heal druid routine for the healbot. I had one but can't find it anymore which spammed healing touch. Are there any plans on making one? Would be very much appreciated! :) 

PS: I already saw the guide to make an own one, but I got 2 left hands for coding, the least I can do is opening editor O:-)

**Comment by Bin4ry1337** [comment]
I can make a druid heal rotation, you can add me on skype for help: bine1339 :)

**Comment by Bin4ry1337** [comment]
Here is a Resto Druid healing profile u can use: http://codepen.io/Bin4ry/pen/jPYjEm
